# Generated by Django 5.2.13 on 2026-05-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='location',
            field=models.CharField(blank=True, help_text='City or area used to show nearby sessions.', max_length=255),
        ),
    ]
