# Generated by Django 5.2.14 on 2026-05-20 13:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0003_alter_sport_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('sports', 'Sports'), ('music', 'Music lessons'), ('tutoring', 'Tutoring')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('price_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('programme', models.ForeignKey(blank=True, help_text='Leave empty for category-wide items (e.g. general sports gear).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='sports.sport')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
