# Generated by Django 5.2.13 on 2026-05-14 12:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('long_description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('room_or_court', models.CharField(blank=True, max_length=255)),
                ('capacity_notes', models.CharField(blank=True, max_length=500)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'venues',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True)),
                ('qualifications', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'coaches',
            },
        ),
        migrations.CreateModel(
            name='ActivityClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('default_capacity', models.PositiveIntegerField(default=12)),
                ('default_duration_minutes', models.PositiveIntegerField(default=60)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('default_price_cents', models.PositiveIntegerField(default=15000, help_text='Smallest currency unit (e.g. cents for ZAR)')),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_classes', to='sports.sport')),
            ],
            options={
                'verbose_name_plural': 'activity classes',
            },
        ),
    ]
