# Generated by Django 5.2.14 on 2026-05-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('music', 'Music lessons'), ('tutoring', 'Tutoring')], db_index=True, default='sports', max_length=20),
        ),
    ]
