# Generated by Django 5.2.14 on 2026-05-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_add_program_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'programme', 'verbose_name_plural': 'programmes'},
        ),
    ]
