# Generated by Django 5.2.14 on 2026-05-20 14:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0003_alter_sport_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramSubcategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sports", "Sports"),
                            ("music", "Music lessons"),
                            ("tutoring", "Tutoring"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "programme subcategory",
                "verbose_name_plural": "programme subcategories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="programsubcategory",
            constraint=models.UniqueConstraint(
                fields=("category", "slug"),
                name="unique_subcategory_slug_per_category",
            ),
        ),
        migrations.AddField(
            model_name="sport",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="programmes",
                to="sports.programsubcategory",
            ),
        ),
    ]
