# Generated by Django 5.2.13 on 2026-05-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_programsubcategory_sport_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(blank=True, db_index=True, help_text='City or suburb for geo filtering.', max_length=255),
        ),
        migrations.AddField(
            model_name='venue',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='maps_url',
            field=models.URLField(blank=True, help_text='Google Maps link for directions.'),
        ),
    ]
