# Generated by Django 5.2.13 on 2026-05-14 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassScheduleRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('recurrence_start_date', models.DateField()),
                ('recurrence_end_date', models.DateField(blank=True, null=True)),
                ('capacity_override', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('activity_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_rules', to='sports.activityclass')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_rules', to='sports.coach')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_rules', to='sports.venue')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='scheduled', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('booking_cutoff_at', models.DateTimeField(blank=True, help_text='Optional; bookings blocked after this instant.', null=True)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='sports.activityclass')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='sports.coach')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='sports.venue')),
                ('schedule_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='scheduling.classschedulerule')),
            ],
            options={
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['starts_at', 'status'], name='scheduling__starts__1672ba_idx')],
            },
        ),
    ]
