# Generated by Django 5.2.13 on 2026-05-14 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0001_initial'),
        ('children', '0001_initial'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('number_of_credits', models.PositiveIntegerField(default=1)),
                ('price_amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('expires_after_days', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_products', to='sports.sport')),
            ],
        ),
        migrations.CreateModel(
            name='CreditLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('purchase', 'Purchase'), ('redemption', 'Redemption'), ('refund', 'Refund'), ('expiry', 'Expiry'), ('adjustment', 'Adjustment')], max_length=20)),
                ('credit_delta', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_ledger_entries', to='bookings.booking')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_ledger', to='children.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_ledger', to='accounts.parentprofile')),
                ('package_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='payments.packageproduct')),
            ],
            options={
                'verbose_name_plural': 'credit ledger entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe')], default='stripe', max_length=32)),
                ('provider_checkout_session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('provider_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially refunded')], db_index=True, default='initiated', max_length=32)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.parentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
